name: python-aos
channels:
  - conda-forge
dependencies:
  - python=3
  - xarray
  - netcdf4
  - cartopy
  - jupyter
  - scipy
  - cmocean
  - pandas
  - cmdline_provenance
  - matplotlib
  - basemap
