name: python-aos
channels:
  - conda-forge
dependencies:
  - python=3
  - xarray
  - netcdf4
  - cartopy
  - jupyter
  - scipy
  - pip:
    - unit_conversion
    - pdb
  - cmocean
  - pandas
  - cmdline_provenance
